Cuckoo Hashtable & Cuckoo Hashtable tests
kurapov-peter/dwarf_bench pull request #5
Opened 2021-08-03 09:49 UTC by Daniel-ND

2021-08-03 12:06 UTC, kurapov-peter requested changes
Very nice overall, need a couple cosmetic changes

2021-08-03 13:21 UTC, Daniel-ND commented on common/dpcpp/cuckoo_hashtable.hpp
> +            return false;
fixed

2021-08-03 13:55 UTC, Daniel-ND commented on common/dpcpp/cuckoo_hashtable.hpp
> +        bool insert(Key key, Val value, size_t cnt) {
By mistake left from when this method was recursive. Removed.

2021-08-03 16:47 UTC, Daniel-ND commented on common/dpcpp/cuckoo_hashtable.hpp
> +        const bool has(Key key) {
Made this method const, by this logic, the method at() also. They both should't modify hashtable.

2021-08-03 17:17 UTC, Daniel-ND commented on common/dpcpp/cuckoo_hashtable.hpp
> +                uint32_t mask, present, major_idx;
Moved these variables to lock & unlock methods. Think that's better.

2021-08-04 08:06 UTC, Daniel-ND commented on common/dpcpp/cuckoo_hashtable.hpp
> +        const Key _EMPTY_KEY;
fixed

2021-08-04 13:47 UTC, kurapov-peter approved these changes
LGTM

2021-08-04 13:47 UTC, kurapov-peter commented on tests/cuckoo_hashtable_tests.cpp
> +#define EMPTY_KEY std::numeric_limits<uint32_t>::max()
Unused?

2021-08-06 14:44 UTC, merged